### ISSUE TITLE
throw err;  ^  Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by boghbogh** [aksonov/react-native-router-flux#1033]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.?? ( ?? latest code)
  -react-native-cli: 1.0.0
  -react-native: 0.26.3
### Expected behaviour

To be able to run the app.
### Actual behaviour

I cannot run the app. I pulled the code. npm install and then react-native run-ios and get a build error

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/Users/XXXXX/react-native-router-flux/node_modules/graceful-fs/polyfills.js:18:9)
    at _runIOS (runIOS.js:51:11)
    at runIOS.js:24:5
    at tryCallTwo (/Users/XXX/react-native-router-flux/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/XXX/react-native-router-flux/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/XXXX/react-native-router-flux/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/XXX/react-native-router-flux/node_modules/react-native/local-cli/cli.js:87:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
### Steps to reproduce
1. clone
2. npm install
3. react-native run-ios

**Comment by quadsurf** [comment]
@boghbogh you get that error when you attempt to install deps and run the app from the root dir...

just cd into the /Example/ dir, install deps, then run it, and you will see the app run without that error
