### ISSUE TITLE
Snapshot test error because of react-native-router-flux

### ISSUE THREAD

**Issue by fumiyasac** [aksonov/react-native-router-flux#1810]
When I do snapshot test, it can't do because of library. 
Is it bug?? 

★package.json

```
{
  "name": "LikeCustomTransition",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.16.0",
    "native-base": "^2.1.0",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.43.3",
    "react-native-parallax-view": "^2.0.6",
    "react-native-router-flux": "^3.38.0",
    "react-native-scrollable-tab-view": "^0.6.3",
    "react-native-snap-carousel": "^2.1.0",
    "react-native-super-grid": "^1.0.2",
    "react-native-timeline-listview": "^0.2.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "15.4.2"
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "/node_modules/(?!native-base|react-native-router-flux|react-native)/"
    ]
  }
}
```

★Error log

```
 FAIL  __tests__/src/components/common/Intro.js
  ● Test suite failed to run

    ENOENT: no such file or directory, stat '/Users/sakaifumiya/Desktop/reactNativeApp/LikeCustomTransition/node_modules/react-native-router-flux/node_modules/react-native/Libraries/Core/ErrorUtils.js'

      at Object.fs.statSync (fs.js:968:11)
      at Object.statSync (node_modules/graceful-fs/polyfills.js:297:22)
      at Object.<anonymous> (node_modules/react-native/jest/setup.js:64:532)
```

- react-native-router-flux v3.38.0
- react-native v0.43.3

**Comment by fumiyasac** [comment]
In addition, I tried to do `sudo` option when I do snapshot test.
Is it related to this incident...?

```
sakaifuiyanoMBP:TravelMemo sakaifumiya$ sudo npm test
Password:

> TravelMemo@0.0.1 test /Users/sakaifumiya/Desktop/reactNativeApp/TravelMemo
> jest

 FAIL  __tests__/src/components/common/CommonHeader.js
  ● Test suite failed to run

    Invariant Violation: Native module cannot be null.

      at invariant (node_modules/fbjs/lib/invariant.js:44:7)
      at Linking.NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:32:1)
      at new Linking (node_modules/react-native/Libraries/Linking/Linking.js:119:141)
      at Object.<anonymous> (node_modules/react-native/Libraries/Linking/Linking.js:191:16)
      at Object.get Linking [as Linking] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:95:22)
      at Object.<anonymous> (node_modules/react-native-experimental-navigation/NavigationRootContainer.js:15:36)
```
