### ISSUE TITLE
jsc-heap-capture name collision

### ISSUE THREAD

**Issue by Un3qual** [aksonov/react-native-router-flux#1830]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.1
- react-native v0.43.3 & 0.44.0
- react v16.0.0-alpha.6

### Expected behaviour
I expect the app to build

### Actual behaviour
Instead, I get this error message:
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: jsc-heap-capture
  Paths: /Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native-router-flux/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json collides with /Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: jsc-heap-capture
  Paths: /Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native-router-flux/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json collides with /Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:159:13)
    at p.getName.then.name (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:134:31)
```

### Steps to reproduce

1. Create an app with the version specified above
2. Run the app from Xcode

**Comment by Un3qual** [comment]
Same thing that @m-revetria mentioned over on #1687

**Comment by pbassut** [comment]
Did you really remove the node_modules from RNRF and ran `react-native run-ios/android` again?

**Comment by Un3qual** [comment]
Yes. When I remove the `mode_modules` folder, it complains that it can't import packages:
```
error: bundling: Error: ENOENT: no such file or directory, open '/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native-router-flux/node_modules/react-native/Libraries/Components/AccessibilityInfo/AccessibilityInfo.ios.js'
    at Object.fs.openSync (fs.js:583:18)
    at Object.fs.readFileSync (fs.js:490:33)
    at Module._readSourceCode (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/Module.js:200:29)
    at Module._getCacheProps (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/Module.js:420:29)
    at Module._readFromTransformCache (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/Module.js:376:29)
    at Module.readCached (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/Module.js:363:25)
    at Promise.resolve.then (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:167:29)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Bundling `index.ios.js`  89.1% (1508/1598), failed.
Error: ENOENT: no such file or directory, open '/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native-router-flux/node_modules/react-native/Libraries/Components/AccessibilityInfo/AccessibilityInfo.ios.js'
    at Object.fs.openSync (fs.js:583:18)
    at Object.fs.readFileSync (fs.js:490:33)
    at Module._readSourceCode (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/Module.js:200:29)
    at Module._getCacheProps (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/Module.js:420:29)
    at Module._readFromTransformCache (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/Module.js:376:29)
    at Module.readCached (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/Module.js:363:25)
    at Promise.resolve.then (/Users/admin/Desktop/Programming/RN/myAppV9/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:167:29)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
Actually, I get that error message regardless of whether or not I remove `myAppv9/node_modules/react-native-router-flux/node_modules`.

**Comment by wuhenwuya** [comment]
+1

**Comment by eyu0415** [comment]
+1

**Comment by georgberecz** [comment]
+1

**Comment by kokokenada** [comment]
+1

**Comment by gtsbgogss** [comment]
+1

**Comment by hnq90** [comment]
+1

Same problem.

**Comment by hnq90** [comment]
+1

Same problem.

**Comment by rodrigocipriani** [comment]
#1809

**Comment by rodrigocipriani** [comment]
#1809 Duplicated

**Comment by hnq90** [comment]
@rodrigocipriani It's not duplicated.

The only correct solution is using previous version (`3.38.0`)...

**Comment by rodrigocipriani** [comment]
@hnq90 I wrote Duplicated because #1809 has the answer.

**Comment by corymayer** [comment]
#1862 Uploaded a new PR that also relaxes the version requirement on react-native
