### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by davojan** [aksonov/react-native-router-flux#2240]
Unable to build react-native-router-flux to prepare PR.

### Version
Tell us which versions you are using: 

- react-native-router-flux v4 master
- react-native v0.45.1
- node v6.11.1
- babel 6.4.5 (babel-core 6.4.5)

### Expected behaviour

dist folder is updated with the changed code

### Actual behaviour

```
npm run build

> react-native-router-flux@4.0.0-beta.18 build /Users/davojan/projects/react-native-router-flux
> babel src -d dist --presets react-native-stage-0/decorator-support

TypeError: [BABEL] src/ActionConst.js: Invalid options type for /Users/davojan/projects/libicraft/react-native-router-flux/node_modules/babel-preset-react-native/index.js
    at Logger.error (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:243:16)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:325:16)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:287:12)
    at OptionManager.addConfig (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-router-flux@4.0.0-beta.18 build: `babel src -d dist --presets react-native-stage-0/decorator-support`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-router-flux@4.0.0-beta.18 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Steps to reproduce
```
git clone https://github.com/aksonov/react-native-router-flux.git
cd react-native-router-flux
yarn               # or npm install
yarn run build     # or npm run build
```

**Comment by aksonov** [comment]
Can't reproduce that.
```
bash-3.2$ yarn
yarn install v0.24.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "0.27.5" while you're on "0.24.5".
$ ./node_modules/.bin/opencollective postinstall

     *** Thank you for using react-native-router-flux! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/react-native-router-flux/donate

                    ***

✨  Done in 15.83s.

bash-3.2$ yarn run build
yarn run v0.24.5
$ babel src -d dist --presets react-native-stage-0/decorator-support 
src/ActionConst.js -> dist/ActionConst.js
src/Drawer.js -> dist/Drawer.js
src/Lightbox.js -> dist/Lightbox.js
src/LightboxNavigator.js -> dist/LightboxNavigator.js
src/Modal.js -> dist/Modal.js
src/NavBar.js -> dist/NavBar.js
src/Reducer.js -> dist/Reducer.js
src/Router.js -> dist/Router.js
src/Scene.js -> dist/Scene.js
src/Stack.js -> dist/Stack.js
src/State.js -> dist/State.js
src/Tabs.js -> dist/Tabs.js
src/Util.js -> dist/Util.js
src/index.js -> dist/index.js
src/navigationStore.js -> dist/navigationStore.js
✨  Done in 2.30s.

```

**Comment by davojan** [comment]
I have yarn 0.27.5 but hardly it's about yarn.
May be babel or node version is important? Please tell yours:
```
node --version
babel --version
```

**Comment by aksonov** [comment]
bash-3.2$ node --version
v7.10.0

bash-3.2$ babel --version
6.24.0 (babel-core 6.24.0)
