### ISSUE TITLE
flux is not working with react-native swiper

### ISSUE THREAD

**Issue by Kiozak** [aksonov/react-native-router-flux#2333]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.2

### Expected behaviour
Hello first , so i was trying to make a like facebook app , everything was going good , i used this code from the Example 

### Actual behaviour
but when i installed react-native-swiper , my app start to force close when ever i tried to click the Button to pass from the first page to the second , is this a kind of bug , or i m a doing something wrong ?
here is Android studio Log :   java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/drawee/view/DraweeHolder;
                                                               at com.facebook.drawee.view.DraweeView.init(DraweeView.java:78)
                                                               at com.facebook.drawee.view.DraweeView.<init>(DraweeView.java:53)
                                                               at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:32)
                                                               at com.facebook.react.views.image.ReactImageView.<init>(ReactImageView.java:182)
                                                               at com.facebook.react.views.image.ReactImageManager.createViewInstance(ReactImageManager.java:76)
                                                               at com.facebook.react.views.image.ReactImageManager.createViewInstance(ReactImageManager.java:34)
                                                               at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
                                                               at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
                                                               at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:150)
                                                               at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:923)
                                                               at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:895)
                                                               at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                               at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                                               at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:586)
                                                               at android.view.Choreographer.doFrame(Choreographer.java:555)
                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5284)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.drawee.view.DraweeHolder" on path: DexPathList[[zip file "/data/app/com.nemesis-1/base.apk"],nativeLibraryDirectories=[/data/app/com.nemesis-1/lib/arm, /vendor/lib, /system/lib]]
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                               at com.facebook.drawee.view.DraweeView.init(DraweeView.java:78) 
                                                               at com.facebook.drawee.view.DraweeView.<init>(DraweeView.java:53) 
                                                               at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:32) 
                                                               at com.facebook.react.views.image.ReactImageView.<init>(ReactImageView.java:182) 
                                                               at com.facebook.react.views.image.ReactImageManager.createViewInstance(ReactImageManager.java:76) 
                                                               at com.facebook.react.views.image.ReactImageManager.createViewInstance(ReactImageManager.java:34) 
                                                               at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46) 
                                                               at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218) 
                                                               at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:150) 
                                                               at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:923) 
                                                               at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:895) 
                                                               at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
                                                               at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136) 
                                                               at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107) 
                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771) 
                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:586) 
                                                               at android.view.Choreographer.doFrame(Choreographer.java:555) 
                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759) 
                                                               at android.os.Handler.handleCallback(Handler.java:739) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                               at android.os.Looper.loop(Looper.java:135) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5284) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697) 
                                                           	Suppressed: java.lang.NoClassDefFoundError: com.facebook.drawee.view.DraweeHolder
                                                               at dalvik.system.DexFile.defineClassNative(Native Method)
                                                               at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                               at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                               at dalvik.system.DexPathList.findClass(DexPathList.java:321)
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                               		... 28 more
                                                           	Suppressed: java.lang.ClassNotFoundException: com.facebook.drawee.view.DraweeHolder
                                                               at java.lang.Class.classForName(Native Method)
                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                               		... 27 more
                                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by Kiozak** [comment]
i found the solution , when i installed both the modules i didn't add **--save** at the last of the command , sorry guys thanks for your time

**Comment by Pylipala** [comment]
Please close the issue if it is solved. Thanks~
