### ISSUE TITLE
Problem with running the Example

### ISSUE THREAD

**Issue by eladcandroid** [aksonov/react-native-router-flux#305]
I'm getting this error:

> [3:52:36 PM] <END>   Crawling File System (2466ms)
[3:52:36 PM] <START> Building in-memory fs for JavaScript
[3:52:40 PM] <END>   Building in-memory fs for JavaScript (3818ms)
[3:52:40 PM] <START> Building in-memory fs for Assets
[3:52:44 PM] <END>   Building in-memory fs for Assets (3672ms)
[3:52:44 PM] <START> Building Haste Map
[3:52:47 PM] <START> Building (deprecated) Asset Map
[3:52:49 PM] <END>   Building (deprecated) Asset Map (1510ms)
Failed to build DependencyGraph: Naming collision detected: /home/elad/react/react-native-router-flux/Example/node_modules/react/node_modules/fbjs/lib/ExecutionEnvironment.js collides with /home/elad/react/react-native-router-flux/Example/node_modules/react-native/node_modules/fbjs/lib/ExecutionEnvironment.js
Error: Naming collision detected: /home/elad/react/react-native-router-flux/Example/node_modules/react/node_modules/fbjs/lib/ExecutionEnvironment.js collides with /home/elad/react/react-native-router-flux/Example/node_modules/react-native/node_modules/fbjs/lib/ExecutionEnvironment.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/home/elad/react/react-native-router-flux/Example/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /home/elad/react/react-native-router-flux/Example/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/home/elad/react/react-native-router-flux/Example/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

**Comment by jandom** [comment]
It seems that `rm -rf node_modules` and reinstall helps some people. Since you haven't provided instructions to reproduce, I can't try to replicate what you've done – also googling for 'DependencyGraph: Naming collision detected' gives a number of helpful pointers
