### ISSUE TITLE
Duplicate module name: AutoFocusUtils

### ISSUE THREAD

**Issue by GeekWeier** [aksonov/react-native-router-flux#849]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.30.2
- react-native v0.25.1

[10:26:52] <START> Building Dependency Graph
[10:26:52] <START> Crawling File System
[10:26:53] <START> find dependencies
[10:27:07] <END>   Crawling File System (14967ms)
[10:27:07] <START> Building in-memory fs for JavaScript
[10:27:08] <END>   Building in-memory fs for JavaScript (1197ms)
[10:27:08] <START> Building in-memory fs for Assets
[10:27:09] <END>   Building in-memory fs for Assets (854ms)
[10:27:09] <START> Building Haste Map
[10:27:09] <START> Building (deprecated) Asset Map
[10:27:09] <END>   Building (deprecated) Asset Map (198ms)
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: AutoFocusUtils
  Paths: /Users/Will/RGSpace/WorkSpace/Sublime/p2pv3m/node_modules/react-native-router-flux/node_modules/react-native-experimental-navigation/node_modules/react/lib/AutoFocusUtils.js collides with /Users/Will/RGSpace/WorkSpace/Sublime/p2pv3m/node_modules/react/lib/AutoFocusUtils.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: AutoFocusUtils
  Paths: /Users/Will/RGSpace/WorkSpace/Sublime/p2pv3m/node_modules/react-native-router-flux/node_modules/react-native-experimental-navigation/node_modules/react/lib/AutoFocusUtils.js collides with /Users/Will/RGSpace/WorkSpace/Sublime/p2pv3m/node_modules/react/lib/AutoFocusUtils.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/Will/RGSpace/WorkSpace/Sublime/p2pv3m/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /Users/Will/RGSpace/WorkSpace/Sublime/p2pv3m/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:125:25
Command /bin/sh failed with exit code 1

** BUILD FAILED **

**Comment by badaz** [comment]
For me, deleting the node_modules/react-native-router-flux/node_modules/react-native-experimental-navigation/node_modules/react folder completely did the trick.

**Comment by rturk** [comment]
@GeekWeier you should really consider using a newer RN version. RN25 & RN26 are not properly supported.

**Comment by cridenour** [comment]
Sounds like @badaz has a working solution. Closing for now. Feel free to comment if this is still an issue!
