### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by wildQueequeg** [aksonov/react-native-router-flux#963]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.32.2
- react-native v^0.27.0

### Expected behaviour
Example iOS project runs

### Actual behaviour
Packager can't start:
/react-native-router-flux/Example/node_modules/react-native/Libraries/react-native/react-native.js:15
if (__DEV__) {
    ^

ReferenceError: __DEV__ is not defined
    at Object.<anonymous> (/Users/jiangyu/react-native-router-flux/Example/node_modules/react-native/Libraries/react-native/react-native.js:15:5)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jiangyu/react-native-router-flux/Example/node_modules/react-native/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/jiangyu/react-native-router-flux/Example/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:309:22
    at Array.map (native)
~
Process terminated. Press <enter> to close the window

### Steps to reproduce

1. npm install in Example
2. run ios project in xcode

**Comment by cridenour** [comment]
Can you try running `react-native upgrade` in that project? This is more of a general react-native error, but it could be our example.

**Comment by new-xd** [comment]
Look at this https://github.com/facebook/react-native/issues/7814

**Comment by derdav3** [comment]
I just tried and it worked... can you run "react-native run-ios"?

**Comment by wildQueequeg** [comment]
Tried `react-native upgrade` and `react-native run-ios`. Getting the same error. Trying out facebook/react-native#7814

**Comment by wildQueequeg** [comment]
Works now!
- Added `babel-preset-react-native` to package.json
- `npm install`
- Using npm2, so I had to remove `Example/node_modules/react-native-router-flux/node_modules/react-native-experimental-navigation/node_modules/react`
- `react-native upgrade` + `react-native run-ios`
